MilkWayIndia/Controllers/BulkUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MilkWayIndia.Models;
using System.IO;
using System.Data;
using System.Data.OleDb;
using System.Configuration;
using System.Data.SqlClient;
using MilkWayIndia.Concrete;
using MilkWayIndia.Entity;
using MilkWayIndia.Abstract;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Web.UI;

namespace MilkWayIndia.Controllers
{
    public class BulkUploadController : Controller
    {
        string excel03 = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source={0};Extended Properties='Excel 8.0;HDR=YES'";
        string excel07 = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties='Excel 8.0;HDR=YES'";
        Helper dHelper = new Helper();
        Product objProduct = new Product();
        clsCommon _clsCommon = new clsCommon();

        private IBulkUpload _BulkRepo;
        private IProduct _ProductRepo;
        public BulkUploadController()
        {
            this._BulkRepo = new BulkUploadRepository();
            this._ProductRepo = new ProductRepository();
        }

        public ActionResult Index()
        {
            var control = Helper.CheckPermission(Request.RawUrl.ToString());
            if (control.IsView == false)
                return Redirect("/notaccess/index");
            if (Request.Cookies["gstusr"] == null)
                return Redirect("/home/login?ReturnURL=" + Request.RawUrl);
            PopulateGrid();
            return View();
        }

        public void PopulateGrid()
        {
            var bulkUpload = _BulkRepo.PendingBulkUpload();
            ViewBag.lstBulkUpload = bulkUpload;
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase postedFile)
        {
            int Count = 0;
            string filePath = string.Empty;
            if (postedFile != null)
            {
                try
                {
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                        Directory.CreateDirectory(path);

                    string extension = Path.GetExtension(postedFile.FileName);
                    string filename = dHelper.RemoveIllegalCharacters(Path.GetFileNameWithoutExtension(postedFile.FileName) + " " + DateTime.Now) + extension;
                    filePath = path + filename;
                    postedFile.SaveAs(filePath);

                    tbl_BulkUpload upload = new tbl_BulkUpload();
                    upload.FileName = postedFile.FileName;
                    upload.FilePath = "/Uploads/" + filename;
                    upload.UploadItem = 0;
                    upload.IsUpload = false;
                    upload.CreatedOn = Helper.indianTime;

                    List<tbl_Product_Temp> list = new List<tbl_Product_Temp>();
                    using (var sreader = new StreamReader(postedFile.InputStream))
                    {
                        string[] headers = sreader.ReadLine().Split(',');
                        while (!sreader.EndOfStream)
                        {
                            int col = 1;
                            string[] rows = sreader.ReadLine().Split(',');
                            tbl_Product_Temp product = new tbl_Product_Temp();
                            if (!string.IsNullOrEmpty(rows[0].ToString()))
                                product.SortOrder = Convert.ToInt32(rows[0].ToString());
                            else product.SortOrder = 0;
                            string _category = "";

                            if (!string.IsNullOrEmpty(rows[1].ToString()))
                                _category = rows[1].ToString() + "|";
                            if (!string.IsNullOrEmpty(rows[2].ToString()))
                                _category = _category + rows[2].ToString();
                            product.CategoryName = _category;
                            product.ProductName = rows[3].ToString(); col = 3;
                            product.ProductImage = rows[4].ToString(); col = 4;

                            if (!string.IsNullOrEmpty(rows[5].ToString()))
                                product.MRP = Convert.ToDecimal(rows[5].ToString());
                            else product.MRP = 0;

                            if (!string.IsNullOrEmpty(rows[6].ToString()))
                                product.SalePrice = Convert.ToDecimal(rows[6].ToString());
                            else product.SalePrice = 0;

                            if (!string.IsNullOrEmpty(rows[7].ToString()))
                                product.PurchasePrice = Convert.ToDecimal(rows[7].ToString());
                            else product.PurchasePrice = 0;

                            if (!string.IsNullOrEmpty(rows[8].ToString()))
                                product.CGST = Convert.ToDecimal(rows[8].ToString());
                            else product.CGST = 0;

                            if (!string.IsNullOrEmpty(rows[9].ToString()))
                                product.SGST = Convert.ToDecimal(rows[9].ToString());
                            else product.SGST = 0;

                            if (!string.IsNullOrEmpty(rows[10].ToString()))
                                product.IGST = Convert.ToDecimal(rows[10].ToString());
                            else product.IGST = 0;

                            if (!string.IsNullOrEmpty(rows[11].ToString()))
                                product.ProfitL = Convert.ToDecimal(rows[11].ToString());
                            else product.ProfitL = 0;

                            if (!string.IsNullOrEmpty(rows[12].ToString()))
                                product.ProfitP = Convert.ToDecimal(rows[12].ToString());
                            else product.ProfitP = 0;

                            if (!string.IsNullOrEmpty(rows[13].ToString()))
                                product.Details = rows[13].ToString();
                            else product.Details = "";

                            if (!string.IsNullOrEmpty(rows[14].ToString()))
                                product.Subcription = Convert.ToDecimal(rows[14].ToString());
                            else product.Subcription = 0;

                            if (!string.IsNullOrEmpty(rows[15].ToString()))
                                product.YoutubeTitle = rows[15].ToString();
                            else product.YoutubeTitle = "";

                            if (!string.IsNullOrEmpty(rows[16].ToString()))
                                product.YoutubeURL = rows[16].ToString();
                            else product.YoutubeURL = "";

                            if (!string.IsNullOrEmpty(rows[17].ToString()))
                                product.Status = Convert.ToBoolean(rows[17].ToString());
                            else product.Status = false;

                            if (!string.IsNullOrEmpty(rows[18].ToString()))
                                product.IsDaily = Convert.ToBoolean(rows[18].ToString());
                            else product.IsDaily = false;

                            decimal? _gst = (product.CGST + product.SGST + product.IGST);
                            decimal? _gstAmount = (product.MRP * _gst) / 100;
                            if (product.ProfitL == 0 && product.ProfitP == 0)
                            {
                                decimal? _profitL = 0;
                                _profitL = product.MRP - product.PurchasePrice;
                                if (product.SalePrice == 0)
                                    product.SalePrice = product.PurchasePrice + _profitL;
                                else
                                    _profitL = product.SalePrice - product.PurchasePrice;
                                product.ProfitL = _profitL;
                                product.Profit = _profitL;
                            }
                            if (product.ProfitP > 0)
                            {
                                decimal? _profit = (product.SalePrice * product.ProfitP) / 100;
                                if (product.SalePrice == 0)
                                {
                                    product.PurchasePrice = product.MRP - _profit;
                                    product.SalePrice = product.PurchasePrice + _profit;
                                }
                                else
                                    product.PurchasePrice = product.SalePrice - _profit;
                                product.Profit = _profit;
                            }
                            if (product.ProfitL > 0)
                            {
                                decimal? _profit = product.ProfitL;
                                if (product.SalePrice == 0)
                                {
                                    product.PurchasePrice = product.MRP - _profit;
                                    product.SalePrice = product.PurchasePrice + _profit;
                                }
                                else
                                    product.PurchasePrice = product.SalePrice - _profit;                                
                                product.Profit = product.ProfitL;
                            }
                            product.CreatedOn = Helper.indianTime;
                            product.IsUpload = false;
                            product.ErrorMessage = "";
                            list.Add(product);
                            Count = Count + 1;
                        }
                    }
                    if (Count > 150)
                        ViewBag.SuccessMsg = "Only upload 150 products...";
                    else
                    {
                        upload.TotalItem = Count;
                        upload.list = list;

MilkWayIndia/Views/BulkUpload/Detail.cshtml
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@section contain
{
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <script>
        $(document).ready(function () {
            var MasterClass = document.getElementById("LiProduct");
            if (MasterClass != null) {
                MasterClass.className = MasterClass.className + " active";

            }
        });
    </script>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Product List</h3>
                    </div>
                    <div class="box-footer text-right">
                        @using (Ajax.BeginForm("UploadProduct", "BulkUpload", null, new AjaxOptions { OnSuccess = "SuccessUpload" }, new { @id = "frmUpload" }))
                        {
                            <input type="hidden" value="@ViewBag.UploadID" name="UploadID" />
                            <button type="submit" class="btn btn-primary">Upload Products</button>
                            <a href="/bulkupload/index" class="btn btn-danger">Back</a>
                        }
                        @Html.Raw(ViewBag.Message)
                    </div>
                    <div class="box-body">
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-bordered table-striped">
                                @{int rowNo = 0;}
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Category</th>
                                        <th>Product Name</th>
                                        <th>MRP</th>
                                        <th>Sale Price</th>
                                        <th>Purchase Price</th>
                                        <th>Profit L</th>
                                        <th>Profit %</th>
                                        <th>Profit</th>
                                        <th>Error</th>
                                        @*<th>Action</th>*@
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (ViewBag.lstProduct != null)
                                    {
                                        foreach (var item in ViewBag.lstProduct)
                                        {
                                            <tr>
                                                <td>@(rowNo += 1)</td>
                                                <td>@item.CategoryName</td>
                                                <td>
                                                    @item.ProductName
                                                </td>
                                                <td>
                                                    @item.MRP
                                                </td>
                                                <td>
                                                    @item.SalePrice
                                                </td>
                                                <td>@item.PurchasePrice</td>
                                                <td>@item.ProfitL</td>
                                                <td>@item.ProfitP</td>
                                                <td>@item.Profit</td>
                                                <td>
                                                    <span class="text-danger">
                                                        @item.ErrorMessage
                                                    </span></td>
                                                @*<td><a href="/BulkUpload/Edit/@item.ID"><i class="fa fa-edit"></i></a></td>*@
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>
    <script>
        $(document).ready(function () {
            $("#loaderbody").addClass('hide');
            $(document).bind('ajaxStart', function () {
                $("#loaderbody").removeClass('hide');
            }).bind('ajaxStop', function () {
                $("#loaderbody").addClass('hide');
            });
        });

        function SuccessUpload() {

        }
    </script>
}

MilkWayIndia/Views/BulkUpload/DownloadProduct.cshtml
@{
    ViewBag.Title = "VendorProductOrder";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@section contain
{
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <script>
        $(document).ready(function () {
            var MasterClass = document.getElementById("ReportLi");
            if (MasterClass != null) {
                MasterClass.className = MasterClass.className + " active";

            }
        });
    </script>
    <link href="~/Content/plugins/datepicker/datepicker3.css" rel="stylesheet" />
    <script src="~/Content/plugins/datepicker/bootstrap-datepicker.js"></script>
    <section class="content-header">
        @if (@TempData["error"] != null)
    {
            <script type="text/javascript">
                alert("@TempData["error"]");
            </script>
        }
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Download Products</h3>
                        </div>
                        <div class="box-body">
                            @using (Ajax.BeginForm("DownloadProduct", "BulkUpload", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "upddiv" }))
                            {
                                <div class="btn-group-vertical ">
                                    <div class="form-group has-feedback">
                                        <select id="ddlSector" name="ddlSector" class="form-control select2">
                                            <option value="0">---Select Sector---</option>
                                            @if (ViewBag.lstSector != null)
                                            {
                                                foreach (System.Data.DataRow drSector in ViewBag.lstSector.Rows)
                                                {
                                                    <option value="@drSector["Id"]">@drSector["SectorName"] </option>
                                                }
                                            }
                                        </select>
                                        @if (ViewBag.SectorId != null)
                                        {
                                            <script>
                                                document.getElementById('ddlSector').value = '@ViewBag.SectorId';
                                            </script>
                                        }
                                    </div>
                                </div>
                                <div class="btn-group-vertical ">
                                    <div class="form-group has-feedback">
                                        <select id="ddlVendor" name="ddlVendor" class="form-control select2">
                                            <option value="0">---Select Vendor---</option>
                                            @if (ViewBag.lstVendor != null)
                                            {
                                                foreach (System.Data.DataRow drVendor in ViewBag.lstVendor.Rows)
                                                {
                                                    <option value="@drVendor["Id"]">@drVendor["FirstName"] @drVendor["LastName"] </option>
                                                }
                                            }
                                        </select>
                                        @if (ViewBag.VendorId != null)
                                        {
                                            <script>
                                                document.getElementById('ddlVendor').value = '@ViewBag.VendorId';
                                            </script>
                                        }
                                    </div>
                                </div>
                                <div class="btn-group-vertical ">
                                    <div class="form-group has-feedback">
                                        <select id="ddlCategory" name="ddlCategory" class="form-control select2">
                                            <option value="0">---Select Category---</option>
                                            @if (ViewBag.lstCategory != null)
                                            {
                                                foreach (var item in ViewBag.lstCategory)
                                                {
                                                    <option value="@item.Value">@item.Text</option>
                                                }
                                            }
                                        </select>
                                        @if (ViewBag.CategoryId != null)
                                        {
                                            <script>
                                                document.getElementById('ddlCategory').value = '@ViewBag.CategoryId';
                                            </script>
                                        }
                                    </div>
                                </div>
                                <div class="btn-group-vertical">
                                    <div class="form-group has-feedback">
                                        <input type="submit" id="btn" value="Download" name="submit" class="btn btn-primary" onclick="return validate();" />
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Upload File</h3>
                        </div>
                        <form role="form" action="/bulkupload/updateproduct" method="post" enctype="multipart/form-data">
                            <div class="box-body">
                                <div id="SuccessMsg" style="color: red">@ViewBag.SuccessMsg</div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Excel File</label>
                                    <input type="file" name="postedFile" id="postedFile" onchange="readURL(this)" required />
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        function readURL(input) {
            var ext = $(input).val().split('.').pop().toLowerCase();
            if ($.inArray(ext, ['csv']) == -1) {
                alert('Invalid file format. Only csv are allowed.');
                $(input).val('');
                return;
            }
        }
    </script>
    <script>
        function validate() {
            var status = true;
            var sector = document.getElementById('ddlSector').value;
            if (sector == '' || sector == null || sector == "0") {
                document.getElementById('ddlSector').style.border = "1px solid #ff0000";
                status = false;
            }
            else {
                document.getElementById('ddlSector').style.border = "";
            }
            var vendor = document.getElementById('ddlVendor').value;
            if (vendor == '' || vendor == null || vendor == "0") {
                document.getElementById('ddlVendor').style.border = "1px solid #ff0000";
                status = false;
            }
            else {
                document.getElementById('ddlVendor').style.border = "";
            }
            var category = document.getElementById('ddlCategory').value;
            if (category == '' || category == null || category == "0") {
                document.getElementById('ddlCategory').style.border = "1px solid #ff0000";
                status = false;
            }
            else {
                document.getElementById('ddlCategory').style.border = "";
            }
            return status;
        }

        $(document).ready(function () {
            $("#ddlSector").change(function () {
                var id = $(this).find('option:selected').val();
                $.post("/Vendor/GetVendorList?id=" + id, function (data) {
                    var ddlVendor = $("[id*=ddlVendor]");
                    var dataRows = JSON.parse(data);
                    ddlVendor.empty().append('<option selected="selected" value="0">---Select---</option>');
                    for (var i = 0; i < dataRows.length; i++) {
                        var row = new Array();
                        var id = dataRows[i].Id;
                        var fname = dataRows[i].FirstName;
                        var lname = dataRows[i].LastName;
                        var opt = new Option(dataRows[i].fname);
                        $('#ddlVendor').append('<option value="' + id + '">' + fname + ' ' + lname + '</option>');
                    }
                });
            });
        });
    </script>
}

MilkWayIndia/Views/BulkUpload/Index.cshtml
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@section contain
{
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <script>
        $(document).ready(function () {
            var MasterClass = document.getElementById("LiProduct");
            if (MasterClass != null) {
                MasterClass.className = MasterClass.className + " active";

            }
        });
    </script>
    @*<section class="content-header">
            <div class="box-header with-border">
                <h3 class="box-title">Product Bulk Upload</h3>
            </div>
        </section>*@
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-6">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Product Bulk Upload</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="/bulkupload/index" method="post" enctype="multipart/form-data">
                        <div class="box-body">
                            <div id="SuccessMsg" style="color: red">@ViewBag.SuccessMsg</div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Excel File</label>
                                <input type="file" name="postedFile" id="postedFile" onchange="readURL(this)" required />
                            </div>
                            <div class="form-group">
                                <a href="~/Uploads/sample.csv">Download Sample File</a>
                            </div>
                        </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Product Bulk Upload List</h3>
                    </div>
                    <div class="box-body">
                        <div class="box-body table-responsive no-padding">
                            <table id="example1" class="table table-bordered table-striped">
                                @{int rowNo = 0;}
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Date</th>
                                        <th>File Name</th>
                                        <th>Total Item</th>
                                        <th>Upload Item</th>
                                        <td></td>
                                        <td>Action</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (ViewBag.lstBulkUpload != null)
                                    {
                                        foreach (var item in ViewBag.lstBulkUpload)
                                        {
                                            <tr>
                                                <td>@(rowNo += 1)</td>
                                                <td>@item.CreatedOn</td>
                                                <td>
                                                    @item.FileName
                                                </td>
                                                <td>
                                                    @item.TotalItem
                                                </td>
                                                <td>
                                                    @item.UploadItem
                                                </td>
                                                <td>
                                                    @if (item.TotalItem != item.UploadItem)
                                                    {
                                                        <a href="/BulkUpload/Detail/@item.ID">Upload</a>
                                                    }
                                                </td>
                                                <td><a href="/BulkUpload/Delete/@item.ID" , onclick="return confirm('Are you sure you want to delete this Data?');"><i class="fa fa-trash-o"></i></a></td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        function readURL(input) {
            var ext = $(input).val().split('.').pop().toLowerCase();
            if ($.inArray(ext, ['csv']) == -1) {
                alert('Invalid file format. Only csv are allowed.');
                $(input).val('');
                return;
            }
        }
    </script>
}