MilkWayIndia/Controllers/AdvertisementController.cs
using MilkWayIndia.Abstract;
using MilkWayIndia.Concrete;
using MilkWayIndia.Entity;
using MilkWayIndia.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MilkWayIndia.Controllers
{
    public class AdvertisementController : Controller
    {
        Helper dHelper = new Helper();
        Dictionary<string, object> res = new Dictionary<string, object>();
        private IAdvertisement _AdvertisementRepo;

        public AdvertisementController()
        {
            this._AdvertisementRepo = new AdvertisementRepository();
        }
        // GET: Advertisement
        public ActionResult Index()
        {
            if (Session["Username"] != null && !string.IsNullOrEmpty(Session["Username"] as string))
            {
                var control = Helper.CheckPermission(Request.RawUrl.ToString());
                if (control.IsView == false)
                    return Redirect("/notaccess/index");

                ViewBag.IsAdmin = control.IsAdmin;
                ViewBag.IsView = control.IsView;
                ViewBag.IsAdd = control.IsAdd;

                var advertisement = PopulateGrid();
                return View(advertisement);
            }
            else
            {
                return Redirect("/home/login?ReturnURL=" + Request.RawUrl);
            }
        }

        public List<tbl_Advertisement> PopulateGrid()
        {
            var advertisement = _AdvertisementRepo.GetAllAdvertisement();
            return advertisement;
        }

        public ActionResult Create()
        {
            if (Session["Username"] != null && !string.IsNullOrEmpty(Session["Username"] as string))
            {
                var control = Helper.CheckPermission(Request.RawUrl.ToString());
                if (control.IsView == false)
                    return Redirect("/notaccess/index");

                ViewBag.IsAdmin = control.IsAdmin;
                ViewBag.IsView = control.IsView;
                ViewBag.IsAdd = control.IsAdd;
                return View();
            }
            else
                return Redirect("/home/login?ReturnURL=" + Request.RawUrl);
        }

        public ActionResult Edit(int? ID)
        {
            if (Session["Username"] != null && !string.IsNullOrEmpty(Session["Username"] as string))
            {
                var control = Helper.CheckPermission(Request.RawUrl.ToString());
                if (control.IsView == false)
                    return Redirect("/notaccess/index");

                AdvertisementModel model = new AdvertisementModel();
                var advertisement = _AdvertisementRepo.GetAdvertisementID(ID);
                if (advertisement != null)
                {                    
                    model.ID = advertisement.ID;
                    model.AdsType = advertisement.AdsType;
                    model.Title = advertisement.Title;
                    model.Mobile = advertisement.Mobile;
                    model.StartDate= advertisement.StartDate == null ? "" : advertisement.StartDate.Value.ToString("yyyy-MM-dd");
                    model.ExpiredDate= advertisement.ExpiredDate == null ? "" : advertisement.ExpiredDate.Value.ToString("yyyy-MM-dd");
                    model.Description = advertisement.Description;
                    model.WebsiteLink = advertisement.WebsiteLink;
                    model.AppLink = advertisement.AppLink;
                    model.PhotoPath = advertisement.PhotoPath;               
                    ViewBag.PhotoPath = advertisement.PhotoPath;                    
                }
                return View(model);
            }
            else
                return Redirect("/home/login?ReturnURL=" + Request.RawUrl);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Create(AdvertisementModel model, HttpPostedFileBase photo)
        {
            if (Session["Username"] != null && !string.IsNullOrEmpty(Session["Username"] as string))
            {                
                var response = InsertUpdate(model, photo);
                if (response.ID > 0)
                    ViewBag.SuccessMsg = "Advertisement Inserted Successfully!!!";
                else
                    ViewBag.SuccessMsg = "Advertisement Not Inserted!!!";
            }
            else
                return Redirect("/home/login?ReturnURL=" + Request.RawUrl);
            return View();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(AdvertisementModel model, HttpPostedFileBase photo)
        {
            if (Session["Username"] != null && !string.IsNullOrEmpty(Session["Username"] as string))
            {
                var response = InsertUpdate(model, photo);
                if (response.ID > 0)
                    ViewBag.SuccessMsg = "Advertisement Updated Successfully!!!";
                else
                    ViewBag.SuccessMsg = "Advertisement Not Inserted!!!";
            }
            else
                return Redirect("/home/login?ReturnURL=" + Request.RawUrl);
            return View();
        }

        [ValidateInput(false)]
        public tbl_Advertisement InsertUpdate(AdvertisementModel model, HttpPostedFileBase photo)
        {
            tbl_Advertisement _ads = new tbl_Advertisement();
            if (photo != null)
            {
                string path = Server.MapPath("~/Image/");
                string extension = Path.GetExtension(photo.FileName);
                string filename = Guid.NewGuid() + extension;
                var filePath = path + filename;
                photo.SaveAs(filePath);
                model.PhotoPath = "/image/" + filename;
                _ads.PhotoPath = model.PhotoPath;
            }
            else
                _ads.PhotoPath = model.PhotoPath;
            _ads.ID = model.ID;
            _ads.AdsType = model.AdsType;
            _ads.Title = model.Title;
            _ads.Mobile = model.Mobile;
            _ads.Description = model.Description;
            _ads.WebsiteLink = model.WebsiteLink;
            _ads.AppLink = model.AppLink;
            _ads.IsDeleted = false;
            if (!string.IsNullOrEmpty(model.StartDate))
                _ads.StartDate = DateTime.ParseExact(model.StartDate, "yyyy-MM-dd", null);
            if (!string.IsNullOrEmpty(model.ExpiredDate))
                _ads.ExpiredDate = DateTime.ParseExact(model.ExpiredDate, "yyyy-MM-dd", null);
            ViewBag.PhotoPath = model.PhotoPath;
            var response = _AdvertisementRepo.SaveAdvertisement(_ads);
            return response;
        }

        public ActionResult Delete(int ID)
        {
            _AdvertisementRepo.DeleteAdvertisement(ID);
            return Redirect("/advertisement/index");
        }
    }
}

MilkWayIndia/Views/Advertisement/Create.cshtml
@model MilkWayIndia.Entity.AdvertisementModel
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@section contain
{
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <link href="~/Content/plugins/datepicker/datepicker3.css" rel="stylesheet" />
    <script src="~/Content/plugins/datepicker/bootstrap-datepicker.js"></script>
    <script>
        $(document).ready(function () {
            var MasterClass = document.getElementById("LiMst");
            if (MasterClass != null) {
                MasterClass.className = MasterClass.className + " active";
            }
        });
    </script>
    <section class="content-header">
        <h1>
            Add Advertisement
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Admin")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Add Advertisement</li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <div class="btn-group-vertical">
                        <a href="/Advertisement/index" class="btn btn-success">Back To Panel</a>
                    </div>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="form-horizontal">
                    @using (Html.BeginForm("Create", "Advertisement", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.Partial("_CreateOrUpdate")
                    }
                </div>
            </div>
        </div>
    </section>
}

MilkWayIndia/Views/Advertisement/Edit.cshtml
@model MilkWayIndia.Entity.AdvertisementModel
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@section contain
{
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <link href="~/Content/plugins/datepicker/datepicker3.css" rel="stylesheet" />
    <script src="~/Content/plugins/datepicker/bootstrap-datepicker.js"></script>
    <script>
        $(document).ready(function () {
            var MasterClass = document.getElementById("LiMst");
            if (MasterClass != null) {
                MasterClass.className = MasterClass.className + " active";
            }
        });
    </script>
    <section class="content-header">
        <h1>
            Edit Advertisement
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Admin")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Edit Advertisement</li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <div class="btn-group-vertical">
                        <a href="/Advertisement/index" class="btn btn-success">Back To Panel</a>
                    </div>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="form-horizontal">
                    @using (Html.BeginForm("Edit", "Advertisement", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.Partial("_CreateOrUpdate")
                    }
                </div>
            </div>
        </div>
    </section>
}

MilkWayIndia/Views/Advertisement/Index.cshtml
@model IEnumerable<MilkWayIndia.Entity.tbl_Advertisement>
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@section contain
{
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <script>
        $(document).ready(function () {
            var MasterClass = document.getElementById("LiMst");
            if (MasterClass != null) {
                MasterClass.className = MasterClass.className + " active";

            }
        });
    </script>
    <section class="content-header">
        <div class="box-header with-border">
            <h3 class="box-title">Advertisement List</h3>
            <div class="box-tools">
                <div class="input-group input-group-sm pull-right">
                    <a href="/Advertisement/Create" class="btn btn-primary pull-right btn-add">Add</a>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="box-body table-responsive no-padding">
                            <table id="example1" class="table table-bordered table-striped">
                                @{int rowNo = 0;}
                                <thead>
                                    <tr>
                                        <th width="40px">No</th>
                                        <th>Title</th>
                                        <th width="80px">Start Date</th>
                                        <th width="80px">Expired Date</th>
                                        <th width="100px">Photo Path</th>
                                        <td width="20px"></td>
                                        <td width="20px"></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>@(rowNo += 1)</td>
                                                <td>@item.Title</td>
                                                <td>
                                                    @item.StartDate
                                                </td>
                                                <td>@item.ExpiredDate</td>
                                                <td><img src='@item.PhotoPath' height="80" /></td>
                                                <td>
                                                    <a href="/Advertisement/Edit/@item.ID"><i class="fa fa-edit"></i></a>
                                                </td>
                                                <td>
                                                    <a href="/Advertisement/Delete/@item.ID" , onclick="return confirm('Are you sure you want to delete this Data?');"><i class="fa fa-trash-o"></i></a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

}

MilkWayIndia/Views/Advertisement/_CreateOrUpdate.cshtml
@model MilkWayIndia.Entity.AdvertisementModel

<!-- bootstrap wysihtml5 - text editor -->
<link href="~/Content/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" />

@Html.HiddenFor(s => s.ID)
<div class="box-body">
    <div class="row">
        <div class="col-md-8">
            <div id="SuccessMsg" style="color: red">@ViewBag.SuccessMsg</div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">Ads type</label>
                <div class="col-sm-6">
                    @Html.DropDownList("AdsType", new List<SelectListItem>
                        {
                            new SelectListItem{ Text="Offers", Value = "1" },
                            new SelectListItem{ Text="Pop Up", Value = "2" }                            
                         }, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">Title</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">Website Link</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.WebsiteLink, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">App Link</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.AppLink, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Mobile</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Mobile, new { @class = "form-control", onkeypress = "return ValidateNumber(event);" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Start Date</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control", type = "date", @value = ViewBag.StartDate })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Expired Date</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.ExpiredDate, new { @class = "form-control", type = "date", @value = ViewBag.ExpiredDate })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="col-sm-3 control-label">Photo</label>
                <div class="col-sm-4">
                    @Html.HiddenFor(m => m.PhotoPath)
                    <input type="file" name="photo" onchange="readURL(this)" />
                    @*<span>Size : 200px * 200px</span>*@
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4">
                    <img id="photo" alt="" src="@ViewBag.PhotoPath" />
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label class="col-sm-2 control-label">Description</label>
                <div class="col-sm-10">
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control textarea", rows = "8" })
                </div>
            </div>
        </div>
    </div>
</div>
<div class="box-footer text-right">
    <input type="submit" value="Save" class="btn btn-primary" onclick="return ValidAdvertisement();" />
</div>

<script>
    function ValidateNumber(e) {
        var keycode = (e.which) ? e.which : e.keyCode;
        if (!(keycode == 8 || keycode == 46) && (keycode < 48 || keycode > 57)) {
            return false;
        }
        return true;
    };

    function ValidAdvertisement() {
        var status = true;
        $('input').removeClass('field-error');
        var Title = document.getElementById("Title").value;
        if (Title == null || Title == "") {
            $('#Title').addClass('field-error');
            status = false;
        }
        var StartDate = document.getElementById("StartDate").value;
        if (StartDate == null || StartDate == "") {
            $('#StartDate').addClass('field-error');
            status = false;
        }
        var ExpiredDate = document.getElementById("ExpiredDate").value;
        if (ExpiredDate == null || ExpiredDate == "") {
            $('#ExpiredDate').addClass('field-error');
            status = false;
        }
        return status;
    }

    function readURL(input) {
        var ext = $(input).val().split('.').pop().toLowerCase();
        if ($.inArray(ext, ['jpg', 'jpeg', 'png']) == -1) {
            alert('Invalid file format. Only jpg and png are allowed.');
            $(input).val('');
            return;
        }

        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#photo').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<script src="~/Content/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script>
    $(function () {
        $('.textarea').wysihtml5()
    })
</script>